services:
  php8.2:
    #image içerisinden kurulum yapılmasını istersek bunu açıyoruz, yoksa yorum satırı yapıyoruz
    #image: php:8.2-fpm
    build:
      context: ./docker/php8.2
    hostname: php8.2
    ports:
      - "10001:9000"
    volumes:
      - ./codes/:/var/www/html
      - ./docker/php8.2/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php8.2/php.ini:/usr/local/etc/php/php.ini
    environment:
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  nginx:
    platform: linux/x86_64
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./codes/:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      -   php8.2

  mysql:
    platform: linux/x86_64
    image: mysql:8.4.2
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    depends_on:
      - mysql
    ports:
      - "8080:80"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: LocalPGSQL
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  mysql_data:
  pgdata: